### ISSUE TITLE
fetch returns error  No such file or directory for several files

### ISSUE THREAD

**Issue by m-idasa** [rust-skia/depot_tools#1]
fetch returns :
 curl: (22) The requested URL returned error: 403 
/home/mahsa/depot_tools/bootstrap_python3: line 32: bootstrap-3.8.0.chromium.8_bin/python3/bin/python3: No such file or directory
cat: /home/mahsa/depot_tools/python3_bin_reldir.txt: No such file or directory
/home/mahsa/depot_tools/vpython3: line 52: /home/mahsa/depot_tools/.cipd_bin/vpython3: No such file or directory

maybe there is a problem with this version!

**Comment by pragmatrix** [comment]
Hello @m-idasa , sorry for not responding earlier, but this repository is not regularly watched and is only a clone for Google's repository. I think you need to post bugs to https://bugs.chromium.org/p/chromium/issues to get a response.

Closing
